name: kiranjaapp_supplier
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: '>=3.0.2 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  firebase_core: ^2.14.0
  flutter_easyloading: ^3.0.5
  image_picker: ^0.8.9
  csc_picker: ^0.2.7
  intl: ^0.18.0
  get_storage: ^2.1.1
  cloud_firestore: ^4.8.1
  firebase_storage: ^11.2.3
  firebase_auth: ^4.6.3
  email_validator: ^2.1.17
  cached_network_image: ^3.2.3
  firebase_ui_firestore: ^1.5.3
  firebase_ui_auth: ^1.4.3
  firebase_ui_database: ^1.3.3
  provider: ^6.0.5
  search_page: ^2.3.0
  flutter_slidable: ^3.0.0
  location: ^5.0.3
  geocoding: ^2.1.0
  geolocator: ^10.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0



# The following section is specific to Flutter packages.
flutter:

 
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/kiranja-logo.png
    - assets/images/apple.png
    - assets/images/google.png
  

  
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
